server:
  port: 8081
bot:
  name: ${app.bot.name}
  token: ${app.bot.token}
feign:
  report:
    host: ${MS_REPORT_HOST:http://localhost:9080/api/v1}
  receipt-collector:
    host: ${MS_RECEIPT_COLLECTOR_HOST:http://localhost:8080/receipt}